#!/usr/bin/env python3
"""Generate the OWNED, corpus-free fixture PDFs that the CI suite asserts against.

Every PDF here is generated by us (no third-party content), committed, and paired with
ground truth in ``fixtures_pdf/groundtruth.json``. Together with demo.pdf (gen_demo.py)
and the synthetic table corpus (gen_tables.py) these reproduce — on data we can share
freely — the coverage the gitignored corpus tests give locally: headings, lists,
figures (raster + vector), links/anchors, two-column reading order, typography
(sub/superscript, accents, de-hyphenation), math-vs-table/heading discrimination, and
word-level span granularity.

Low-level canvas (absolute text positioning) is used so the layout matches how text is
really placed and extraction is deterministic; the two-column fixture uses platypus
frames (per-block ``cm``) so it also exercises the CTM path; the links fixture is a
hand-written PDF so it carries a real ``/Names /Dests`` name tree (named-destination
anchors, which reportlab does not emit).

    python tests/gen_fixtures.py        # needs reportlab + pillow (dev only)
"""
import json
import os

from PIL import Image, ImageDraw
from reportlab.lib.pagesizes import letter
from reportlab.lib.utils import simpleSplit
from reportlab.pdfgen import canvas
from reportlab.platypus import BaseDocTemplate, Frame, PageTemplate, Paragraph
from reportlab.lib.styles import getSampleStyleSheet

OUT = os.path.join(os.path.dirname(__file__), "fixtures_pdf")
os.makedirs(OUT, exist_ok=True)
PAGE_W, PAGE_H = letter
LM = 72
COL_W = PAGE_W - 2 * LM
BODY_F, BODY_S, LEAD = "Helvetica", 10.5, 14
GT = {}


def title(c, text):
    c.setFont("Helvetica-Bold", 19)
    c.drawCentredString(PAGE_W / 2, PAGE_H - 80, text)


def para(c, text, y, indent=0, gap=8, font=BODY_F, size=BODY_S, width=None):
    c.setFont(font, size)
    w = (width if width is not None else COL_W) - indent
    for line in simpleSplit(text, font, size, w):
        c.drawString(LM + indent, y, line)
        y -= LEAD
    return y - gap


def heading(c, text, y, size=13, gap=6):
    c.setFont("Helvetica-Bold", size)
    c.drawString(LM, y, text)
    return y - (size + gap)


# --------------------------------------------------------------------------- headings
def gen_headings():
    pdf = os.path.join(OUT, "headings.pdf")
    c = canvas.Canvas(pdf, pagesize=letter)
    title(c, "Structural Heading Showcase")
    y = PAGE_H - 120
    y = heading(c, "Abstract", y)
    y = para(c, "This abstract is ordinary body prose introducing the document so the "
                "section heading above is recognised as a canonical top-level head.", y)
    y = heading(c, "1 Introduction", y)
    y = para(c, "The introduction is plain paragraph text under a numbered section "
                "heading and should be extracted as a paragraph in reading order.", y)
    y = heading(c, "1.1 Background", y, size=12)
    y = para(c, "A subsection beneath the introduction, one level deeper in the outline.", y)
    y = heading(c, "1.1.1 Prior Work", y, size=11)
    y = para(c, "A sub-subsection, the deepest numbered level in this document.", y)
    y = heading(c, "2 Methods", y)
    y = para(c, "Another top-level numbered section with its own body paragraph.", y)
    traps = [
        "Smith et al. (2019) demonstrated the approach on several datasets in detail.",
        "This is an ordinary declarative sentence of body prose that ends with a period.",
        "We thank J. K. Lee and M. R. Patel for helpful discussions and feedback here.",
    ]
    for t in traps:
        y = para(c, t, y)
    y = heading(c, "References", y)
    y = para(c, "Vaswani A. and others. Attention is all you need. Conference, 2017.", y, gap=2)
    c.showPage()
    c.save()
    GT["headings.pdf"] = {
        "title": "Structural Heading Showcase",
        "headings": [
            {"text": "Abstract", "tag": "h2"},
            {"text": "1 Introduction", "tag": "h2"},
            {"text": "1.1 Background", "tag": "h3"},
            {"text": "1.1.1 Prior Work", "tag": "h4"},
            {"text": "2 Methods", "tag": "h2"},
            {"text": "References", "tag": "h2"},
        ],
        "not_headings": traps,
    }


# ------------------------------------------------------------------------------ lists
def gen_lists():
    pdf = os.path.join(OUT, "lists.pdf")
    c = canvas.Canvas(pdf, pagesize=letter)
    title(c, "List Showcase")
    y = PAGE_H - 120
    wrapped = ("Star-marked delta wraps onto a second line so its continuation is folded "
               "back into the same list item rather than splitting off as a paragraph.")
    star = ["Star-marked alpha is the first unordered item.",
            "Star-marked beta is the second unordered item.",
            "Star-marked gamma is the third unordered item.",
            wrapped]
    numbered = ["First ordered step in the procedure.",
                "Second ordered step in the procedure.",
                "Third ordered step in the procedure."]
    colon = ["Question one introduced after a colon line.",
             "Question two introduced after a colon line."]
    # '*' is a recognised weak bullet; reportlab cannot emit a real U+2022 bullet in
    # Helvetica (it maps to 0x7f), so the unordered list uses '*'.
    y = para(c, "An unordered list, including one wrapped item:", y, gap=4)
    for b in star:
        y = para(c, "*  " + b, y, indent=18, gap=3)
    y -= 6
    y = para(c, "An ordered numbered list:", y, gap=4)
    for i, n in enumerate(numbered, 1):
        y = para(c, f"{i}. {n}", y, indent=18, gap=3)
    y -= 6
    # colon-introduced: a ':' line immediately precedes numbered items carrying labels.
    y = para(c, "The study asks the following questions:", y, gap=4)
    for i, q in enumerate(colon, 1):
        y = para(c, f"{i}. {q}", y, indent=18, gap=3)
    c.showPage()
    c.save()
    GT["lists.pdf"] = {
        "numbered": numbered, "colon": colon,
        "wrapped_snippet": "folded back into the same list item",
        "unordered_items": star, "ordered_items": numbered + colon,
    }


def gen_runin():
    """A bold run-in head inline with the body it introduces, where that body wraps with
    a line-break hyphen. The head must become its own <hN>, and the body must flow as ONE
    paragraph with the hyphenated word rejoined (not split into the head's leftover <p>
    plus an orphaned continuation)."""
    pdf = os.path.join(OUT, "runin.pdf")
    c = canvas.Canvas(pdf, pagesize=letter)
    title(c, "Run-in Heads")
    y = PAGE_H - 120
    y = para(c, "The section below opens with a bold run-in head on the same line as its "
                "body text, a common style in academic papers.", y)
    # run-in head (bold) + body on the SAME line, body wraps with a hyphen
    t = c.beginText(LM, y)
    t.setFont("Helvetica-Bold", 11); t.textOut("Model Architecture ")
    t.setFont(BODY_F, BODY_S); t.textOut("the framework uses a modular architec-")
    c.drawText(t)
    y -= LEAD
    c.setFont(BODY_F, BODY_S)
    c.drawString(LM, y, "ture that lets downstream components be extended and maintained freely.")
    c.showPage()
    c.save()
    GT["runin.pdf"] = {
        "head": "Model Architecture",
        "rejoined": "modular architecture that lets downstream",
        "not_present": "architec- ture",
    }


def gen_footnotes():
    """Body text followed by a block of footnotes in smaller type at the page bottom —
    must be gathered into one <aside>, each footnote split on its leading marker, not
    left as loose body <p>s."""
    pdf = os.path.join(OUT, "footnotes.pdf")
    c = canvas.Canvas(pdf, pagesize=letter)
    title(c, "Footnotes Demo")
    y = PAGE_H - 120
    bodies = [
        "This document ends with a block of footnotes set in smaller type at the bottom of "
        "the page, the way academic papers present them, well clear of the body text above.",
        "The body text is set at the normal body size, so the smaller footnote block below "
        "is clearly distinguishable both by its font size and by its position on the page.",
        "A reader scanning the page sees the main argument first and the supporting "
        "footnotes, each with its reference marker, gathered together at the very bottom.",
    ]
    for b in bodies:
        y = para(c, b, y, gap=10)
    foots = [
        "1  First footnote explains a referenced detail in smaller type.",
        "2  Second footnote points readers to a related resource for context.",
        "3  Third footnote adds a final clarifying remark about the method.",
    ]
    fy = 120
    c.setFont("Helvetica", 8)
    for f in foots:
        c.drawString(LM, fy, f)
        fy -= 11
    c.showPage()
    c.save()
    GT["footnotes.pdf"] = {
        "foot_snippets": ["First footnote explains a referenced detail",
                          "Second footnote points readers to a related",
                          "Third footnote adds a final clarifying remark"],
    }


def gen_twolists():
    """Two numbered lists with a real paragraph between them. Regression guard: the
    intervening paragraph must stay its own <p> (not be swallowed into the first list's
    last <li>) and the two lists must remain separate, intact lists."""
    pdf = os.path.join(OUT, "twolists.pdf")
    c = canvas.Canvas(pdf, pagesize=letter)
    title(c, "Two Lists Separated By Prose")
    y = PAGE_H - 120
    first = ["Initialize the system before starting the run.",
             "Run the main computation loop to completion."]
    middle = ("Between the two lists sits this ordinary paragraph of body prose, which "
              "must remain its own paragraph and never be swallowed into the list above.")
    second = ["Validate the computed results for correctness.",
              "Report the final summary output to the user."]
    y = para(c, "The first procedure has the following steps:", y, gap=4)
    for i, n in enumerate(first, 1):
        y = para(c, f"{i}. {n}", y, indent=18, gap=3)
    y -= 8
    y = para(c, middle, y)
    y -= 4
    y = para(c, "A second, unrelated procedure has its own steps:", y, gap=4)
    for i, n in enumerate(second, 1):
        y = para(c, f"{i}. {n}", y, indent=18, gap=3)
    c.showPage()
    c.save()
    GT["twolists.pdf"] = {
        "first": first, "second": second,
        "middle_snippet": "must remain its own paragraph and never be swallowed",
    }


# ---------------------------------------------------------------------------- figures
def _bar_png(path):
    img = Image.new("RGB", (300, 190), "white")
    d = ImageDraw.Draw(img)
    d.rectangle([8, 8, 291, 181], outline="black", width=2)
    d.rectangle([50, 110, 110, 175], fill=(60, 110, 200))
    d.rectangle([170, 60, 230, 175], fill=(200, 90, 70))
    img.save(path)


def gen_figures():
    """Page 1: a raster image + caption + an inline cross-reference. Page 2: a vector
    chart (>=6 paths) with axis labels and a 90deg-rotated y-axis title + caption. One
    figure per page so each caption has an unambiguous nearest figure."""
    pdf = os.path.join(OUT, "figures.pdf")
    png = os.path.join(OUT, "_bar.png")
    _bar_png(png)
    c = canvas.Canvas(pdf, pagesize=letter)
    title(c, "Figure Showcase")
    y = PAGE_H - 120
    y = para(c, "This document contains a raster figure and a vector figure. As shown in "
                "Figure 1 the bars differ in height, which the analysis discusses below.", y)
    img_w, img_h = 230, 146
    c.drawImage(png, LM, y - img_h, width=img_w, height=img_h)
    y -= img_h + 14
    c.setFont("Helvetica", 9.5)
    c.drawString(LM, y, "Figure 1: A raster bar chart comparing two measured groups.")
    c.showPage()
    # page 2 — vector figure
    y = PAGE_H - 120
    ox, oy, vw, vh = LM + 50, y - 150, 220, 130
    c.setLineWidth(1)
    c.line(ox, oy, ox + vw, oy)
    c.line(ox, oy, ox, oy + vh)
    for i in range(1, 4):
        gy = oy + vh * i / 4
        c.line(ox, gy, ox + vw, gy)
    c.setFillColorRGB(0.25, 0.45, 0.8)
    for i, bh in enumerate((40, 95, 65, 110)):
        c.rect(ox + 20 + i * 48, oy, 28, bh, fill=1, stroke=1)
    c.setFillColorRGB(0, 0, 0)
    c.setFont("Helvetica", 8)
    for i, lab in enumerate(("Q1", "Q2", "Q3", "Q4")):
        c.drawString(ox + 28 + i * 48, oy - 11, lab)
    c.saveState()
    c.translate(ox - 16, oy + vh / 2 - 20)
    c.rotate(90)
    c.setFont("Helvetica", 8)
    c.drawString(0, 0, "Amplitude")
    c.restoreState()
    yc = oy - 24
    c.setFont("Helvetica", 9.5)
    c.drawString(LM, yc, "Figure 2: A vector line chart with a rotated axis title.")
    c.showPage()
    c.save()
    os.remove(png)
    GT["figures.pdf"] = {
        "fig1_caption": "Figure 1: A raster bar chart comparing two measured groups.",
        "fig2_caption": "Figure 2: A vector line chart with a rotated axis title.",
        "rotated_label": "Amplitude",
        "inline_xref": "As shown in Figure 1 the bars differ",
        "n_figures": 2,
    }


def _vector_chart(c, ox, oy, vw, vh):
    c.setLineWidth(1)
    c.line(ox, oy, ox + vw, oy)
    c.line(ox, oy, ox, oy + vh)
    for i in range(1, 4):
        c.line(ox, oy + vh * i / 4, ox + vw, oy + vh * i / 4)
    c.setFillColorRGB(0.25, 0.45, 0.8)
    for i, bh in enumerate((40, 95, 65, 110)):
        c.rect(ox + 20 + i * 48, oy, 28, min(bh, vh - 4), fill=1, stroke=1)
    c.setFillColorRGB(0, 0, 0)


def gen_figure_hier():
    """Hierarchical figure/table numbers ("Figure 2.3.1", "Table 0.1-1") must be preserved
    WHOLE in the id (fig-2-3-1 / tab-0-1-1) — not truncated to the leading integer (the NASA
    databook bug). Plus a figure-less caption that must still emit inside <figure>, not as a
    bare <p>."""
    pdf = os.path.join(OUT, "figures_hier.pdf")
    c = canvas.Canvas(pdf, pagesize=letter)
    title(c, "Hierarchical Figure Numbers")
    y = PAGE_H - 130
    _vector_chart(c, LM + 50, y - 120, 210, 110)
    y -= 120 + 8
    c.setFont("Helvetica", 9.5)
    c.drawString(LM, y, "Figure 2.3.1: A hierarchical numbered figure.")
    c.showPage()
    c.setFont("Helvetica", 9.5)
    c.drawString(LM, PAGE_H - 130, "Table 0.1-1: A hierarchical numbered table.")
    c.drawString(LM, PAGE_H - 170, "Figure 6: A caption that is linked even with no graphic here.")
    c.showPage()
    c.save()
    GT["figures_hier.pdf"] = {
        "fig_id": "fig-2-3-1", "tab_id": "tab-0-1-1",
        "fig_caption": "Figure 2.3.1", "tab_caption": "Table 0.1-1",
        "linked_no_graphic": "Figure 6",
    }


def gen_figure_continued():
    """A multi-page continuation: "Figure 4.—Continued" on a later page must NOT emit a new
    (duplicate) caption/id — only the original "Figure 4" caption survives."""
    pdf = os.path.join(OUT, "figures_continued.pdf")
    c = canvas.Canvas(pdf, pagesize=letter)
    title(c, "Continued Figures")
    y = PAGE_H - 130
    _vector_chart(c, LM + 50, y - 120, 210, 110)
    y -= 120 + 8
    c.setFont("Helvetica", 9.5)
    c.drawString(LM, y, "Figure 4: The original caption of the continued figure.")
    c.showPage()
    y = PAGE_H - 130
    _vector_chart(c, LM + 50, y - 120, 210, 110)
    y -= 120 + 8
    c.setFont("Helvetica", 9.5)
    c.drawString(LM, y, "Figure 4.—Continued")
    c.showPage()
    c.save()
    GT["figures_continued.pdf"] = {"caption": "Figure 4", "dup_id": "fig-4-2"}


def gen_figure_nodot():
    """Broadened caption labels: "Fig 5" (no dot) and Nature "Figure 7 |" are captions; an
    inline "As shown in Fig 5 …" body reference is NOT."""
    pdf = os.path.join(OUT, "figures_nodot.pdf")
    c = canvas.Canvas(pdf, pagesize=letter)
    title(c, "Caption Label Variants")
    y = PAGE_H - 130
    y = para(c, "As shown in Fig 5 the trend continues steadily across every measured "
                "quarter of the study period.", y)
    _vector_chart(c, LM + 50, y - 120, 210, 110)
    y -= 120 + 8
    c.setFont("Helvetica", 9.5)
    c.drawString(LM, y, "Fig 5 A figure caption written without a dot after Fig.")
    c.showPage()
    y = PAGE_H - 130
    _vector_chart(c, LM + 50, y - 120, 210, 110)
    y -= 120 + 8
    c.setFont("Helvetica", 9.5)
    c.drawString(LM, y, "Figure 7 | A Nature-style separator caption.")
    c.showPage()
    c.save()
    GT["figures_nodot.pdf"] = {
        "nodot_id": "fig-5", "nature_id": "fig-7",
        "inline_xref": "As shown in Fig 5 the trend",
    }


def gen_lof_dotleader():
    """A 'List of Figures' page: each entry looks like a caption ('Figure N: title …') but
    its tail is a DOT-LEADER run ending in a page number. These must NOT become <figure>
    shells — they're a table of contents, not captions. The wrapped variant (title on line 1,
    leaders on line 2) is the common real-world shape (the thesis case)."""
    pdf = os.path.join(OUT, "lof_dotleader.pdf")
    c = canvas.Canvas(pdf, pagesize=letter)
    title(c, "List of Figures")
    y = PAGE_H - 130
    c.setFont("Helvetica", 11)
    # single-line entry
    c.drawString(LM, y, "Figure 1.1: Overview of the study area . . . . . . . . . . . . . . . 3")
    y -= LEAD
    # wrapped entry — leaders on the continuation line just below
    c.drawString(LM, y, "Figure 2.3: A considerably longer descriptive title that wraps onto")
    y -= LEAD
    c.drawString(LM + 18, y, "a second line before the leaders ................................ 17")
    c.showPage()
    c.save()
    GT["lof_dotleader.pdf"] = {
        "entry_text": "Overview of the study area",
        "wrapped_text": "considerably longer descriptive title",
        "n_figures": 0,
    }


def gen_small_vector_fig():
    """A SMALL vector diagram (below the strong figure bar of 72x54pt: ~52x40pt, a few drawn
    paths) WITH a 'Figure 1:' caption directly beneath. The caption-aware recovery must
    promote it to a real <figure> containing <svg>/<path> — not drop it as a stray mark."""
    pdf = os.path.join(OUT, "small_vector_fig.pdf")
    c = canvas.Canvas(pdf, pagesize=letter)
    title(c, "Small Diagram")
    y = PAGE_H - 140
    y = para(c, "The mapping between the two objects is sketched in the small diagram below.", y)
    ox, oy = LM + 40, y - 44
    c.setLineWidth(1)
    c.ellipse(ox, oy, ox + 22, oy + 16)            # node A
    c.ellipse(ox + 30, oy + 22, ox + 52, oy + 38)  # node B
    c.line(ox + 22, oy + 8, ox + 30, oy + 30)      # an arrow shaft between them
    c.line(ox + 30, oy + 30, ox + 26, oy + 26)     # arrowhead
    y = oy - 14
    c.setFont("Helvetica", 9.5)
    c.drawString(LM, y, "Figure 1: A small diagram of the mapping between two objects.")
    c.showPage()
    c.save()
    GT["small_vector_fig.pdf"] = {
        "caption": "Figure 1: A small diagram of the mapping between two objects.",
        "n_figures": 1,
    }


def gen_no_spurious_figs():
    """Precision gate: a prose page with incidental tiny marks (a short underline rule, a
    small box) and NO figure caption anywhere. Weak vector candidates must NOT be promoted
    without an adjacent caption — the page must emit ZERO <figure> elements. Page 2 is a
    positive control (the same tiny diagram WITH a caption → exactly one figure), proving the
    gate discriminates rather than blanket-rejecting."""
    pdf = os.path.join(OUT, "no_spurious_figs.pdf")
    c = canvas.Canvas(pdf, pagesize=letter)
    title(c, "Prose With Incidental Marks")
    y = PAGE_H - 140
    y = para(c, "This page is ordinary running prose. It contains a couple of incidental "
                "vector marks that are not figures and have no caption near them.", y)
    c.setLineWidth(1)
    c.line(LM, y, LM + 60, y)             # a short underline rule
    y -= 30
    c.rect(LM, y - 18, 28, 18, stroke=1, fill=0)  # a small box
    y -= 40
    para(c, "The narrative continues afterwards without referring to any figure at all.", y)
    c.showPage()
    # page 2 — positive control: the same small diagram WITH a caption
    y = PAGE_H - 140
    ox, oy = LM + 40, y - 44
    c.setLineWidth(1)
    c.ellipse(ox, oy, ox + 22, oy + 16)
    c.ellipse(ox + 30, oy + 22, ox + 52, oy + 38)
    c.line(ox + 22, oy + 8, ox + 30, oy + 30)
    y = oy - 14
    c.setFont("Helvetica", 9.5)
    c.drawString(LM, y, "Figure 1: The control diagram that does have a caption.")
    c.showPage()
    c.save()
    GT["no_spurious_figs.pdf"] = {"page1_figures": 0, "total_figures": 1}


def gen_figures_onepage():
    """Both figures (raster ABOVE, vector BELOW), each with its own caption directly
    beneath it, on ONE page. Regression guard for caption→figure anchoring: the captions
    must bind to the figure each sits under, not get swapped by a top-edge distance."""
    pdf = os.path.join(OUT, "figures_onepage.pdf")
    png = os.path.join(OUT, "_bar2.png")
    _bar_png(png)
    c = canvas.Canvas(pdf, pagesize=letter)
    title(c, "Two Figures On One Page")
    y = PAGE_H - 120
    img_w, img_h = 220, 140
    c.drawImage(png, LM, y - img_h, width=img_w, height=img_h)
    y -= img_h + 14
    c.setFont("Helvetica", 9.5)
    c.drawString(LM, y, "Figure 1: A raster bar chart comparing two measured groups.")
    y -= 34
    _vector_chart(c, LM + 50, y - 120, 210, 110)
    y -= 120 + 8
    c.setFont("Helvetica", 9.5)
    c.drawString(LM, y, "Figure 2: A vector line chart of the same measurements.")
    c.showPage()
    c.save()
    os.remove(png)
    GT["figures_onepage.pdf"] = {
        "fig1_caption": "Figure 1: A raster bar chart comparing two measured groups.",
        "fig2_caption": "Figure 2: A vector line chart of the same measurements.",
    }


# ------------------------------------------------------------------------------ links
def _assemble_pdf(objs, path):
    """Write a minimal PDF from {objnum: bytes} (numbers contiguous from 1)."""
    body = bytearray(b"%PDF-1.5\n%\xe2\xe3\xcf\xd3\n")
    offsets = {}
    for num in sorted(objs):
        offsets[num] = len(body)
        body += b"%d 0 obj\n" % num + objs[num] + b"\nendobj\n"
    xref_off = len(body)
    n = max(objs) + 1
    body += b"xref\n0 %d\n0000000000 65535 f \n" % n
    for num in range(1, n):
        body += b"%010d 00000 n \n" % offsets[num]
    body += b"trailer\n<< /Size %d /Root 1 0 R >>\nstartxref\n%d\n%%%%EOF\n" % (n, xref_off)
    with open(path, "wb") as f:
        f.write(bytes(body))


def gen_mathfonts():
    """Hand-written PDF that exercises math glyph recovery (reportlab can't emit CM math
    fonts). Four show-ops, each in a different path:
      F1 CMSY10 (no encoding/ToUnicode) → bytes 0x14 0x15 0x21 0x32  → ≤ ≥ → ∈
      F2 CMMI10 (no encoding/ToUnicode) → bytes 0x0b 0x16 0x15 0x40  → α μ λ ∂
      F3 PazoMath /Differences → glyph NAMES summation/integral/alpha/lessequal → ∑ ∫ α ≤
      F4 Helvetica raw C1 bytes 0x97 0x92 → — ’
    """
    pdf = os.path.join(OUT, "mathfonts.pdf")
    content = (b"BT /F1 12 Tf 72 720 Td <14152132> Tj ET\n"
               b"BT /F2 12 Tf 72 700 Td <0b161540> Tj ET\n"
               b"BT /F3 12 Tf 72 680 Td <01020304> Tj ET\n"
               b"BT /F4 12 Tf 72 660 Td <9792> Tj ET")
    objs = {
        1: b"<< /Type /Catalog /Pages 2 0 R >>",
        2: b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
        3: (b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << "
            b"/F1 5 0 R /F2 6 0 R /F3 7 0 R /F4 8 0 R >> >> /Contents 4 0 R >>"),
        4: b"<< /Length %d >>\nstream\n%s\nendstream" % (len(content), content),
        5: b"<< /Type /Font /Subtype /Type1 /BaseFont /AAAAAA+CMSY10 >>",
        6: b"<< /Type /Font /Subtype /Type1 /BaseFont /BBBBBB+CMMI10 >>",
        7: (b"<< /Type /Font /Subtype /Type1 /BaseFont /CCCCCC+PazoMath /Encoding << "
            b"/Type /Encoding /Differences [1 /summation /integral /alpha /lessequal] >> >>"),
        8: b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
    }
    _assemble_pdf(objs, pdf)
    GT["mathfonts.pdf"] = {
        "cmsy": "≤≥→∈", "cmmi": "αμλ∂", "diff_names": "∑∫α≤", "c1": "—’",
    }


def gen_links():
    """Hand-written PDF carrying a real /Names /Dests name tree: an external URI link
    and an internal GoTo to a NAMED destination ("cite.smith2020") on page 2. This is
    the citation-anchor path reportlab can't emit — the internal link must resolve to a
    #slug anchor, never #page-N."""
    pdf = os.path.join(OUT, "links.pdf")
    c1 = (b"BT /F1 12 Tf 72 700 Td (Visit our project homepage for downloads and docs.) Tj "
          b"0 -22 Td (See the Smith 2020 reference and the Methods section below.) Tj ET")
    c2 = (b"BT /F1 14 Tf 72 720 Td (Methods) Tj /F1 12 Tf 72 690 Td "
          b"(This destination section is where the cite anchor resolves, not a page number.) Tj ET")
    objs = {
        1: b"<< /Type /Catalog /Pages 2 0 R /Names << /Dests 8 0 R >> >>",
        2: b"<< /Type /Pages /Kids [3 0 R 5 0 R] /Count 2 >>",
        3: (b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] "
            b"/Resources << /Font << /F1 7 0 R >> >> /Contents 4 0 R /Annots [9 0 R 10 0 R] >>"),
        4: b"<< /Length %d >>\nstream\n%s\nendstream" % (len(c1), c1),
        5: (b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] "
            b"/Resources << /Font << /F1 7 0 R >> >> /Contents 6 0 R >>"),
        6: b"<< /Length %d >>\nstream\n%s\nendstream" % (len(c2), c2),
        7: b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
        8: b"<< /Names [ (cite.smith2020) [5 0 R /XYZ 72 730 0] ] >>",
        9: (b"<< /Type /Annot /Subtype /Link /Rect [72 696 420 714] /Border [0 0 0] "
            b"/A << /S /URI /URI (https://example.com/distillpdf) >> >>"),
        10: (b"<< /Type /Annot /Subtype /Link /Rect [72 674 420 692] /Border [0 0 0] "
             b"/A << /S /GoTo /D (cite.smith2020) >> >>"),
    }
    _assemble_pdf(objs, pdf)
    GT["links.pdf"] = {
        "uri": "https://example.com/distillpdf",
        "dest_name": "cite.smith2020",
        "dest_page": 2,
        "uri_text": "Visit our project homepage",
        "internal_text": "Methods section",
    }


# --------------------------------------------------------------------------- pagelabels
def gen_pagelabels():
    """A hand-written PDF carrying a real ``/PageLabels`` number tree (reportlab cannot emit
    one). Four pages: front matter labelled lowercase-roman ``i, ii`` (style ``/r``), then the
    body labelled arabic ``1, 2`` (style ``/D``) restarting at 1. The model build's
    ``page_labels`` reader fills ``pages[n].labels.pdf`` from this, so distill → ``read --pages
    ii`` / ``find --pages 1`` resolve a LABEL to its physical page (the Wave-3 gap: no owned
    fixture carried /PageLabels). Each page has one short heading + body line so it yields real
    sections/blocks to read and find."""
    pdf = os.path.join(OUT, "pagelabels.pdf")

    def page_content(head, body):
        return (b"BT /F1 16 Tf 72 720 Td (%s) Tj ET\n"
                b"BT /F1 11 Tf 72 690 Td (%s) Tj ET" % (head, body))

    pages = [
        (b"Preface", b"The preface is front matter on roman page i of the document."),
        (b"Acknowledgements", b"Acknowledgements continue the front matter on roman page ii."),
        (b"Introduction", b"The introduction opens the body on arabic page 1 of the work."),
        (b"Methods", b"The methods section is the body content on arabic page 2 here."),
    ]
    # Object plan: 1 catalog, 2 pages-tree, 3 font, 4..7 page dicts, 8..11 content streams,
    # 12 PageLabels dict. Page kids 4,5,6,7.
    objs = {
        1: b"<< /Type /Catalog /Pages 2 0 R /PageLabels 12 0 R >>",
        2: b"<< /Type /Pages /Kids [4 0 R 5 0 R 6 0 R 7 0 R] /Count 4 >>",
        3: b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
        12: (b"<< /Nums [ 0 << /S /r >> 2 << /S /D /St 1 >> ] >>"),
    }
    for i, (head, body) in enumerate(pages):
        page_num = 4 + i
        content_num = 8 + i
        objs[page_num] = (
            b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] "
            b"/Resources << /Font << /F1 3 0 R >> >> /Contents %d 0 R >>" % content_num)
        c = page_content(head, body)
        objs[content_num] = b"<< /Length %d >>\nstream\n%s\nendstream" % (len(c), c)
    _assemble_pdf(objs, pdf)
    GT["pagelabels.pdf"] = {
        "labels": {1: "i", 2: "ii", 3: "1", 4: "2"},  # physical page -> /PageLabels label
        "roman_pages": ["i", "ii"],
        "arabic_pages": ["1", "2"],
        "page_ii_text": "front matter on roman page ii",
        "page_arabic1_text": "opens the body on arabic page 1",
    }


# -------------------------------------------------------------------------- typography
def gen_typography():
    """Superscript / subscript (via text rise so they stay on one line), accented Latin
    characters, and de-hyphenation across a line break."""
    pdf = os.path.join(OUT, "typography.pdf")
    c = canvas.Canvas(pdf, pagesize=letter)
    title(c, "Typography Showcase")
    y = PAGE_H - 120
    y = para(c, "This fixture exercises scripts, accented characters and de-hyphenation.", y)
    # superscript on one line via setRise
    t = c.beginText(LM, y)
    t.setFont(BODY_F, 12); t.textOut("The relation E = mc")
    t.setRise(4); t.setFont(BODY_F, 7); t.textOut("2")
    t.setRise(0); t.setFont(BODY_F, 12); t.textOut(" links energy and mass.")
    c.drawText(t)
    y -= LEAD + 6
    # subscript on one line via setRise
    t = c.beginText(LM, y)
    t.setFont(BODY_F, 12); t.textOut("The molecule H")
    t.setRise(-3); t.setFont(BODY_F, 7); t.textOut("2")
    t.setRise(0); t.setFont(BODY_F, 12); t.textOut("O is common.")
    c.drawText(t)
    y -= LEAD + 6
    y = para(c, "Accented words: café, résumé, naïve, Pérez, fjord — all intact.",
             y, size=12)
    # de-hyphenation: hyphen at line end, continuation on the next line of one paragraph
    c.setFont(BODY_F, 12)
    c.drawString(LM, y, "The pipeline performs auto-")
    y -= LEAD
    c.drawString(LM, y, "matic reconstruction of words that hyphenation split across lines.")
    c.showPage()
    c.save()
    GT["typography.pdf"] = {
        "accents": ["café", "résumé", "naïve", "Pérez", "fjord"],
        "dehyphenated": "automatic",
        "not_present": "auto- matic",
        "superscript_base": "mc",
        "subscript_base": "H",
    }


# ------------------------------------------------------------------------- two columns
def gen_twocol():
    """Two-column body prose via platypus frames (each flowable cm-positioned). The
    whole left column must be read before the right column, and the page must NOT be
    mistaken for a table."""
    pdf = os.path.join(OUT, "twocol.pdf")
    styles = getSampleStyleSheet()
    body = styles["BodyText"]
    left = ["LEFTONE Reading order in a two-column layout must follow each column from "
            "top to bottom before crossing to the next column, which this fixture checks.",
            "LEFTTWO The second left-column paragraph continues with ordinary body prose "
            "so the left column has a clear and substantial vertical extent on the page.",
            "LEFTTHREE The third left-column paragraph closes this side of the page before "
            "the reader crosses the central gutter into the right-hand column of text."]
    right = ["RIGHTONE The right column is read only after the entire left column has been "
             "consumed, the precise reading-order property that this fixture is verifying.",
             "RIGHTTWO The second right-column paragraph adds more flowing body prose to "
             "keep the two columns close in height and the central gutter clearly empty.",
             "RIGHTTHREE The final right-column paragraph ends the page with further plain "
             "sentences so neither column is unusually short relative to the other one."]
    story = [Paragraph(p, body) for p in left + right]
    doc = BaseDocTemplate(pdf, pagesize=letter, topMargin=110, bottomMargin=72)
    fw = (COL_W - 36) / 2
    fh = PAGE_H - 110 - 72
    doc.addPageTemplates(PageTemplate(frames=[
        Frame(LM, 72, fw, fh, id="L"),
        Frame(LM + fw + 36, 72, fw, fh, id="R"),
    ]))
    doc.build(story)
    GT["twocol.pdf"] = {
        "order": ["LEFTONE", "LEFTTWO", "LEFTTHREE", "RIGHTONE", "RIGHTTWO", "RIGHTTHREE"],
    }


def gen_twocol_fullwidth_header():
    """A full-width title + abstract spanning the WHOLE text measure, sitting ABOVE a
    two-column body. The header crosses the central gutter, so it has no vertical gap
    there: the layout MUST peel it off with a horizontal cut FIRST, then apply the
    vertical column cut to the body only. Reading order must be header → entire left
    column → right column. Pre-fix the full-width header defeats the gutter test and the
    page falls to a single band, interleaving the columns L/R line-by-line."""
    pdf = os.path.join(OUT, "twocol_fullwidth.pdf")
    c = canvas.Canvas(pdf, pagesize=letter)
    top = PAGE_H - 72
    # Full-width header: a title line + an abstract paragraph wrapped at the FULL text
    # width (so each line crosses the page center / column gutter).
    c.setFont("Helvetica-Bold", 14)
    c.drawString(LM, top, "HEADERSTART A Full-Width Title Spanning Both Columns")
    abstract = ("This abstract runs the full width of the text block, well across the central "
                "gutter, so it cannot belong to either column and must be peeled off above the "
                "two-column body before the columns are read. HEADEREND closes the header band.")
    c.setFont("Helvetica", 10)
    y = top - 24
    for ln in simpleSplit(abstract, "Helvetica", 10, COL_W):
        c.drawString(LM, y, ln)
        y -= 13
    # Two-column body below the header. Gutter straddles the page center (x ≈ 306).
    body_top = y - 24
    lx, rx = LM, 320
    left = ("LEFTSTART the entire left column of the body is read top to bottom before the "
            "right column, after the full-width header above it. each line is ordinary body "
            "prose that fills its narrow measure so the column is clearly distinct from the "
            "header that spans the whole page. we add several lines so the body columns are "
            "tall and unmistakably real columns. LEFTEND closes the left column.")
    right = ("RIGHTSTART the right column follows only after the whole left column, and only "
             "after the full-width header has been emitted first of all. it likewise wraps as "
             "body prose filling its measure, line after line, so the two columns are similar "
             "in height and the gutter between them stays clear. RIGHTEND closes the right.")
    for i, ln in enumerate(simpleSplit(left, "Helvetica", 10, 210)):
        c.drawString(lx, body_top - i * 13, ln)
    for i, ln in enumerate(simpleSplit(right, "Helvetica", 10, 210)):
        c.drawString(rx, body_top - i * 13, ln)
    c.showPage()
    c.save()
    GT["twocol_fullwidth.pdf"] = {
        "order": ["HEADERSTART", "HEADEREND", "LEFTSTART", "LEFTEND", "RIGHTSTART", "RIGHTEND"],
    }


def gen_rotated_image_fig():
    """A vector chart with a small raster placed ROTATED 90° inside it (an axis label that the
    source flattened to a bitmap and set sideways — the Kaspersen 'Temp (Celsius)' case). The
    composited <image> must carry a `transform="matrix(...)"` so the pixels are rotated, not
    stretched into an axis-aligned box (which mangles a rotated label)."""
    pdf = os.path.join(OUT, "rotated_image.pdf")
    png = os.path.join(OUT, "_lbl.png")
    img = Image.new("RGB", (160, 40), "white")
    ImageDraw.Draw(img).text((6, 12), "TEMPLABEL", fill="black")
    img.save(png)
    c = canvas.Canvas(pdf, pagesize=letter)
    title(c, "Rotated Image Label")
    ox, oy, vw, vh = LM + 40, PAGE_H - 320, 240, 150
    _vector_chart(c, ox, oy, vw, vh)  # vector ink (axes/bars) → qualifies as a figure
    # place the label raster rotated 90° just inside the chart's right edge. Rendered ≥24pt on
    # both sides (90×38) so it clears the tiny-tile filter.
    c.saveState()
    c.translate(ox + vw - 10, oy + 20)
    c.rotate(90)
    c.drawImage(png, 0, 0, width=90, height=38)
    c.restoreState()
    c.setFont("Helvetica", 9.5)
    c.drawString(LM, oy - 18, "Figure 1: A chart whose right-axis label is a rotated raster.")
    c.showPage()
    c.save()
    os.remove(png)
    GT["rotated_image.pdf"] = {"caption": "Figure 1: A chart whose right-axis label is a rotated raster."}


def gen_twocol_tight():
    """A TIGHT two-column page set in Times-Roman (a Standard-14 font with NO /Widths) with a
    narrow gutter AND a centered page number sitting in that gutter — the SEC/PRL regime.
    Two fixes must combine to read it column-by-column: (1) Standard-14 AFM widths (else the
    flat 0.5-em guess overshoots and closes the gutter), and (2) the crossing-tolerant gutter
    (else the centered page number splits the lane into sub-threshold halves). Pre-fix this
    interleaves L/R line-by-line."""
    pdf = os.path.join(OUT, "twocol_tight.pdf")
    c = canvas.Canvas(pdf, pagesize=letter)
    c.setFont("Times-Roman", 11)
    lx, rx = 72, 320          # two columns; gutter ≈ left-col-right-edge..rx
    top = PAGE_H - 90
    left = ("LEFTSTART the entire left column is read top to bottom before the right; "
            "each line is ordinary justified body prose that reaches the column edge so a "
            "naive width guess would overshoot the narrow central gutter and merge the "
            "columns. we add many lines so the columns are tall enough to be real columns "
            "and not a short caption that should stay on one line. LEFTEND closes the left.")
    right = ("RIGHTSTART the right column must follow only after the whole left column, the "
             "reading-order property under test here. it likewise wraps as justified prose "
             "filling its measure to the right margin, line after line, so that the two "
             "columns are comparable in height and the gutter between them stays clear "
             "except for the page number. RIGHTEND closes the right column of the page.")
    lines_l = simpleSplit(left, "Times-Roman", 11, 220)
    lines_r = simpleSplit(right, "Times-Roman", 11, 225)
    for i, ln in enumerate(lines_l):
        c.drawString(lx, top - i * 14, ln)
    for i, ln in enumerate(lines_r):
        c.drawString(rx, top - i * 14, ln)
    c.drawCentredString(PAGE_W / 2, 60, "7")  # centered page number in the gutter band
    c.showPage()
    c.save()
    GT["twocol_tight.pdf"] = {"order": ["LEFTSTART", "LEFTEND", "RIGHTSTART", "RIGHTEND"]}


def gen_yflip_page():
    """A page laid out under a Y-FLIP CTM (`[1 0 0 -1 0 H]`, top-left origin) so y grows
    DOWNWARD — the layout convention of many SEC/corporate PDF generators. The five marker
    lines are drawn top-to-bottom; the extracted reading order must be ONE..FIVE. On the
    pre-fix build this reads FIVE..ONE (the catastrophic global bottom-to-top reversal)."""
    pdf = os.path.join(OUT, "yflip.pdf")
    c = canvas.Canvas(pdf, pagesize=letter)
    c.saveState()
    c.transform(1, 0, 0, -1, 0, PAGE_H)  # top-left origin; larger y = lower on the page
    c.setFont("Helvetica", 12)
    for i, word in enumerate(["YFLIPONE", "YFLIPTWO", "YFLIPTHREE", "YFLIPFOUR", "YFLIPFIVE"]):
        c.drawString(72, 90 + i * 70, f"{word} marker paragraph of ordinary body text on the page.")
    c.restoreState()
    c.showPage()
    c.save()
    GT["yflip.pdf"] = {
        "order": ["YFLIPONE", "YFLIPTWO", "YFLIPTHREE", "YFLIPFOUR", "YFLIPFIVE"],
    }


# ------------------------------------------------------------------------------- math
def gen_math():
    """An ASCII display equation (relational '=', an equation number) that must NOT
    become a table or a heading, and a 'Theorem 1.' lead that must NOT be a standalone
    heading. Symbols are ASCII so built-in Helvetica renders them faithfully."""
    pdf = os.path.join(OUT, "math.pdf")
    c = canvas.Canvas(pdf, pagesize=letter)
    title(c, "Convergence Analysis")
    y = PAGE_H - 120
    y = heading(c, "1 Analysis", y)
    y = para(c, "We bound the loss with the following inequality, derived in the appendix.", y)
    # equation with a real subscript (text rise) so this math doc keeps its notation
    t = c.beginText(LM + 40, y)
    t.setFont(BODY_F, 12); t.textOut("L(w) = S(w) + a * R(x")
    t.setFont(BODY_F, 8); t.setRise(-3); t.textOut("i")
    t.setRise(0); t.setFont(BODY_F, 12); t.textOut(") + b      (1)")
    c.drawText(t)
    y -= LEAD + 8
    y = para(c, "Theorem 1. The estimator is consistent under the stated assumptions and "
                "converges to the true parameter as the sample size grows without bound.", y)
    y = para(c, "The remaining discussion is ordinary body prose following the theorem "
                "statement and should be extracted as a paragraph in reading order.", y)
    c.showPage()
    c.save()
    GT["math.pdf"] = {
        "title": "Convergence Analysis",
        "section": "1 Analysis",
        "equation_fragment": "S(w)",
        "theorem_text": "The estimator is consistent under the stated assumptions",
    }


# -------------------------------------------------------------------------- frontmatter
def gen_frontmatter():
    """An academic-paper first page: a large title, an author line with SUPERSCRIPT
    affiliation markers, NUMBERED affiliation lines (plus an interleaved e-mail), an
    ``Abstract:`` block and a ``Keywords:`` line, then a numbered body section. Exercises
    the front-matter <header> + metadata() path: title/authors+orgs/abstract/keywords are
    pulled into <header> (authors linked to their organisation), the e-mail is dropped,
    and the numbered section stays in the body."""
    pdf = os.path.join(OUT, "frontmatter.pdf")
    c = canvas.Canvas(pdf, pagesize=letter)
    c.setFont("Helvetica-Bold", 17)
    c.drawCentredString(PAGE_W / 2, PAGE_H - 80, "A Study of Example Phenomena in Test Documents")
    y = PAGE_H - 112
    # author line with superscript affiliation markers (text rise keeps them on the line)
    def author(t, name, mark):
        t.setFont("Helvetica", 11)
        t.textOut(name)
        t.setRise(4)
        t.setFont("Helvetica", 7)
        t.textOut(mark)
        t.setRise(0)
    t = c.beginText(LM, y)
    author(t, "A. B. First", "1")
    t.setFont("Helvetica", 11); t.textOut(", ")
    author(t, "C. D. Second", "2")
    t.setFont("Helvetica", 11); t.textOut(", ")
    author(t, "E. F. Third", "1")
    c.drawText(t)
    y -= LEAD + 6
    c.setFont("Helvetica", 10)
    c.drawString(LM, y, "1 University of Example, Example City, Exampleland"); y -= 12
    c.drawString(LM, y, "2 Institute of Testing, Test Town, Testland"); y -= 12
    c.drawString(LM, y, "(e-mail: first@example.edu)"); y -= 20
    abstract = ("Abstract: This paper presents a self-contained academic-style fixture used to "
                "verify front-matter extraction. It states a goal, summarises a method, and "
                "reports a result in ordinary prose so the abstract is captured as a single "
                "block separate from the body that follows it.")
    y = para(c, abstract, y, size=9.5, gap=6)
    y = para(c, "Keywords: testing, extraction, metadata, fixtures", y, size=9.5, gap=12)
    y = heading(c, "1 Introduction", y)
    y = para(c, "The introduction is ordinary body prose under a numbered section heading and "
                "must remain in the body, not the header.", y)
    c.showPage()
    c.save()
    GT["frontmatter.pdf"] = {
        "title": "A Study of Example Phenomena in Test Documents",
        "authors": [
            {"name": "A. B. First", "affiliation_contains": "University of Example"},
            {"name": "C. D. Second", "affiliation_contains": "Institute of Testing"},
            {"name": "E. F. Third", "affiliation_contains": "University of Example"},
        ],
        "abstract_contains": "verify front-matter extraction",
        "keywords": ["testing", "extraction", "metadata", "fixtures"],
        "body_contains": "ordinary body prose under a numbered section",
        "email_fragment": "first@example.edu",
    }


# ----------------------------------------------------------------- profile-driven heads
def gen_profile_heads():
    """Section headers set in a DISTINCT, non-bold font only slightly larger than body
    (≈1.14× — below the old fixed 1.18× ratio gate) and NOT flagged bold. The fixed-
    threshold detector misses these; the document style profile recognises the heading
    face from the size·font cluster and promotes them to <h2>. Body is Helvetica; the
    title is large bold Helvetica; section heads are Times-Roman 12 over a 10.5 body."""
    pdf = os.path.join(OUT, "profile_heads.pdf")
    c = canvas.Canvas(pdf, pagesize=letter)
    c.setFont("Helvetica-Bold", 18)
    c.drawCentredString(PAGE_W / 2, PAGE_H - 80, "Profile Driven Heading Detection")
    y = PAGE_H - 120
    heads = ["Background and Motivation", "Method and Materials", "Results and Discussion"]
    for hd in heads:
        # heading: Times-Roman 12 (distinct font, non-bold, 1.14x of the 10.5 body)
        c.setFont("Times-Roman", 12)
        c.drawString(LM, y, hd)
        y -= 18
        y = para(c, "This section body is ordinary Helvetica prose at the body size, set "
                    "below a heading whose only cue is a distinct font slightly larger than "
                    "body — no bold, no numbering — which the style profile must catch.", y)
        y -= 6
    c.showPage()
    c.save()
    GT["profile_heads.pdf"] = {
        "title": "Profile Driven Heading Detection",
        "section_heads": heads,
        "body_snippet": "ordinary Helvetica prose at the body size",
    }


# ---------------------------------------------------------------------------- numeric
def gen_numeric():
    """A borderless numeric table for word-span granularity (no span may pack >1 numeric
    token) and decimal integrity (a decimal must never render as ' : ')."""
    pdf = os.path.join(OUT, "numeric.pdf")
    c = canvas.Canvas(pdf, pagesize=letter)
    title(c, "Numeric Results")
    y = PAGE_H - 130
    headers = ["System", "Acc", "F1", "Loss"]
    rows = [["BaseNet", "84.6", "83.4", "0.21"],
            ["WideNet", "88.2", "87.9", "0.18"],
            ["DeepNet", "91.5", "90.7", "0.15"],
            ["MegaNet", "92.3", "91.8", "0.12"]]
    col_x = [LM, LM + 150, LM + 220, LM + 290]
    c.setFont("Helvetica-Bold", 10)
    for cx, h in zip(col_x, headers):
        c.drawString(cx, y, h)
    y -= LEAD
    c.setFont("Helvetica", 10)
    for row in rows:
        for cx, cell in zip(col_x, row):
            c.drawString(cx, y, cell)
        y -= LEAD
    c.showPage()
    c.save()
    GT["numeric.pdf"] = {
        "header": headers, "rows": rows,
        "decimals": ["84.6", "0.21", "92.3", "0.12"],
    }


def gen_heading_traps():
    """Lines drawn in the HEADING face (bold, larger than body) that must NOT be promoted
    to headings — the content-based rejection filters in detect_header. An equation
    fragment, a single-letter symbol soup, an author/collaboration byline, and a clause
    are each heading-styled but content-disqualified; a genuine canonical section
    ("Introduction") in the same face must still be a heading, proving the filters
    discriminate rather than blanket-reject heading-styled lines."""
    pdf = os.path.join(OUT, "heading_traps.pdf")
    c = canvas.Canvas(pdf, pagesize=letter)
    title(c, "Heading Trap Showcase")
    y = PAGE_H - 120
    y = heading(c, "Introduction", y)  # genuine canonical section → must stay a heading
    y = para(c, "Ordinary body prose under the real section so it anchors a true heading.", y)
    traps = [
        "x = y + z",                       # equation fragment: relation, no real words
        "a b c d e f",                     # symbol/letter soup: single-char tokens
        "The ATLAS Collaboration",         # author/collaboration byline
        "The result was set during the run",  # a clause, not a section name
    ]
    for t in traps:
        y = heading(c, t, y)               # drawn in the heading face — must NOT promote
        y = para(c, "Following body paragraph so the trap sits like a section head.", y)
    c.showPage()
    c.save()
    GT["heading_traps.pdf"] = {
        "headings": [{"text": "Introduction", "tag": "h2"}],
        "not_headings": traps,
    }


def gen_sec_structure():
    """A mini SEC-filing layout that locks the global pre-detection pass (plan_headings)
    and the PART/Item anchors:
      - "PART I" / "Item 1. Business" / "Item 1A. Risk Factors" must be headings (Reliable
        SEC anchors), at section/subsection level;
      - a genuine larger-style section ("Financial Overview") must stay a heading;
      - a flood of >90 short bold line-item lines in ONE shared style must be DISTRUSTED
        as an emphasis/label style → none of them is a heading.
    Mirrors the real failure where a filing's bold line-item face is matched by hundreds of
    financial rows and floods the output with spurious <h4>."""
    pdf = os.path.join(OUT, "sec_structure.pdf")
    c = canvas.Canvas(pdf, pagesize=letter)
    title(c, "Acme Corporation Annual Report")
    y = PAGE_H - 120
    y = heading(c, "PART I", y, size=15)
    y = heading(c, "Item 1. Business", y, size=13)
    y = para(c, "Body prose describing the business operations of the company in detail.", y)
    y = heading(c, "Item 1A. Risk Factors", y, size=13)
    y = para(c, "Risk factor discussion written as ordinary paragraph prose for the filing.", y)
    y = heading(c, "Financial Overview", y, size=15)
    y = para(c, "A short overview paragraph introducing the financial statements below.", y)
    labels = ["Net product sales", "Cost of sales", "Gross profit", "Research and development",
              "Selling and marketing", "General and administrative", "Operating loss",
              "Interest income", "Interest expense", "Other income", "Provision for taxes",
              "Net loss", "Total assets", "Total liabilities", "Cash and equivalents"]
    for i in range(100):  # > the absolute distrust floor (90)
        if y < 90:
            c.showPage()
            y = PAGE_H - 72
        y = heading(c, labels[i % len(labels)], y, size=12, gap=3)
    c.showPage()
    c.save()
    GT["sec_structure.pdf"] = {
        "anchors": ["PART I", "Item 1. Business", "Item 1A. Risk Factors"],
        "genuine": ["Financial Overview"],
        "flood": labels,
    }


def main():
    gen_headings()
    gen_heading_traps()
    gen_sec_structure()
    gen_lists()
    gen_runin()
    gen_footnotes()
    gen_twolists()
    gen_figures()
    gen_figures_onepage()
    gen_figure_hier()
    gen_figure_continued()
    gen_figure_nodot()
    gen_lof_dotleader()
    gen_small_vector_fig()
    gen_no_spurious_figs()
    gen_links()
    gen_pagelabels()
    gen_typography()
    gen_twocol()
    gen_twocol_tight()
    gen_twocol_fullwidth_header()
    gen_rotated_image_fig()
    gen_yflip_page()
    gen_math()
    gen_mathfonts()
    gen_numeric()
    gen_frontmatter()
    gen_profile_heads()
    with open(os.path.join(OUT, "groundtruth.json"), "w") as f:
        json.dump(GT, f, indent=2)
    print(f"generated {len(GT)} fixture PDFs + groundtruth.json -> {OUT}")


if __name__ == "__main__":
    main()
