#!/usr/bin/env python3
"""Generate the OWNED, corpus-free fixture PDFs that the CI suite asserts against.

Every PDF here is generated by us (no third-party content), committed, and paired with
ground truth in ``fixtures_pdf/groundtruth.json``. Together with demo.pdf (gen_demo.py)
and the synthetic table corpus (gen_tables.py) these reproduce — on data we can share
freely — the coverage the gitignored corpus tests give locally: headings, lists,
figures (raster + vector), links/anchors, two-column reading order, typography
(sub/superscript, accents, de-hyphenation), math-vs-table/heading discrimination, and
word-level span granularity.

Low-level canvas (absolute text positioning) is used so the layout matches how text is
really placed and extraction is deterministic; the two-column fixture uses platypus
frames (per-block ``cm``) so it also exercises the CTM path; the links fixture is a
hand-written PDF so it carries a real ``/Names /Dests`` name tree (named-destination
anchors, which reportlab does not emit).

    python tests/gen_fixtures.py        # needs reportlab + pillow (dev only)
"""
import json
import os

from PIL import Image, ImageDraw
from reportlab.lib.pagesizes import letter
from reportlab.lib.utils import simpleSplit
from reportlab.pdfgen import canvas
from reportlab.platypus import BaseDocTemplate, Frame, PageTemplate, Paragraph
from reportlab.lib.styles import getSampleStyleSheet

OUT = os.path.join(os.path.dirname(__file__), "fixtures_pdf")
os.makedirs(OUT, exist_ok=True)
PAGE_W, PAGE_H = letter
LM = 72
COL_W = PAGE_W - 2 * LM
BODY_F, BODY_S, LEAD = "Helvetica", 10.5, 14
GT = {}


def title(c, text):
    c.setFont("Helvetica-Bold", 19)
    c.drawCentredString(PAGE_W / 2, PAGE_H - 80, text)


def para(c, text, y, indent=0, gap=8, font=BODY_F, size=BODY_S, width=None):
    c.setFont(font, size)
    w = (width if width is not None else COL_W) - indent
    for line in simpleSplit(text, font, size, w):
        c.drawString(LM + indent, y, line)
        y -= LEAD
    return y - gap


def heading(c, text, y, size=13, gap=6):
    c.setFont("Helvetica-Bold", size)
    c.drawString(LM, y, text)
    return y - (size + gap)


# --------------------------------------------------------------------------- headings
def gen_headings():
    pdf = os.path.join(OUT, "headings.pdf")
    c = canvas.Canvas(pdf, pagesize=letter)
    title(c, "Structural Heading Showcase")
    y = PAGE_H - 120
    y = heading(c, "Abstract", y)
    y = para(c, "This abstract is ordinary body prose introducing the document so the "
                "section heading above is recognised as a canonical top-level head.", y)
    y = heading(c, "1 Introduction", y)
    y = para(c, "The introduction is plain paragraph text under a numbered section "
                "heading and should be extracted as a paragraph in reading order.", y)
    y = heading(c, "1.1 Background", y, size=12)
    y = para(c, "A subsection beneath the introduction, one level deeper in the outline.", y)
    y = heading(c, "1.1.1 Prior Work", y, size=11)
    y = para(c, "A sub-subsection, the deepest numbered level in this document.", y)
    y = heading(c, "2 Methods", y)
    y = para(c, "Another top-level numbered section with its own body paragraph.", y)
    traps = [
        "Smith et al. (2019) demonstrated the approach on several datasets in detail.",
        "This is an ordinary declarative sentence of body prose that ends with a period.",
        "We thank J. K. Lee and M. R. Patel for helpful discussions and feedback here.",
    ]
    for t in traps:
        y = para(c, t, y)
    y = heading(c, "References", y)
    y = para(c, "Vaswani A. and others. Attention is all you need. Conference, 2017.", y, gap=2)
    c.showPage()
    c.save()
    GT["headings.pdf"] = {
        "title": "Structural Heading Showcase",
        "headings": [
            {"text": "Abstract", "tag": "h2"},
            {"text": "1 Introduction", "tag": "h2"},
            {"text": "1.1 Background", "tag": "h3"},
            {"text": "1.1.1 Prior Work", "tag": "h4"},
            {"text": "2 Methods", "tag": "h2"},
            {"text": "References", "tag": "h2"},
        ],
        "not_headings": traps,
    }


# ------------------------------------------------------------------------------ lists
def gen_lists():
    pdf = os.path.join(OUT, "lists.pdf")
    c = canvas.Canvas(pdf, pagesize=letter)
    title(c, "List Showcase")
    y = PAGE_H - 120
    wrapped = ("Star-marked delta wraps onto a second line so its continuation is folded "
               "back into the same list item rather than splitting off as a paragraph.")
    star = ["Star-marked alpha is the first unordered item.",
            "Star-marked beta is the second unordered item.",
            "Star-marked gamma is the third unordered item.",
            wrapped]
    numbered = ["First ordered step in the procedure.",
                "Second ordered step in the procedure.",
                "Third ordered step in the procedure."]
    colon = ["Question one introduced after a colon line.",
             "Question two introduced after a colon line."]
    # '*' is a recognised weak bullet; reportlab cannot emit a real U+2022 bullet in
    # Helvetica (it maps to 0x7f), so the unordered list uses '*'.
    y = para(c, "An unordered list, including one wrapped item:", y, gap=4)
    for b in star:
        y = para(c, "*  " + b, y, indent=18, gap=3)
    y -= 6
    y = para(c, "An ordered numbered list:", y, gap=4)
    for i, n in enumerate(numbered, 1):
        y = para(c, f"{i}. {n}", y, indent=18, gap=3)
    y -= 6
    # colon-introduced: a ':' line immediately precedes numbered items carrying labels.
    y = para(c, "The study asks the following questions:", y, gap=4)
    for i, q in enumerate(colon, 1):
        y = para(c, f"{i}. {q}", y, indent=18, gap=3)
    c.showPage()
    c.save()
    GT["lists.pdf"] = {
        "numbered": numbered, "colon": colon,
        "wrapped_snippet": "folded back into the same list item",
        "unordered_items": star, "ordered_items": numbered + colon,
    }


def gen_twolists():
    """Two numbered lists with a real paragraph between them. Regression guard: the
    intervening paragraph must stay its own <p> (not be swallowed into the first list's
    last <li>) and the two lists must remain separate, intact lists."""
    pdf = os.path.join(OUT, "twolists.pdf")
    c = canvas.Canvas(pdf, pagesize=letter)
    title(c, "Two Lists Separated By Prose")
    y = PAGE_H - 120
    first = ["Initialize the system before starting the run.",
             "Run the main computation loop to completion."]
    middle = ("Between the two lists sits this ordinary paragraph of body prose, which "
              "must remain its own paragraph and never be swallowed into the list above.")
    second = ["Validate the computed results for correctness.",
              "Report the final summary output to the user."]
    y = para(c, "The first procedure has the following steps:", y, gap=4)
    for i, n in enumerate(first, 1):
        y = para(c, f"{i}. {n}", y, indent=18, gap=3)
    y -= 8
    y = para(c, middle, y)
    y -= 4
    y = para(c, "A second, unrelated procedure has its own steps:", y, gap=4)
    for i, n in enumerate(second, 1):
        y = para(c, f"{i}. {n}", y, indent=18, gap=3)
    c.showPage()
    c.save()
    GT["twolists.pdf"] = {
        "first": first, "second": second,
        "middle_snippet": "must remain its own paragraph and never be swallowed",
    }


# ---------------------------------------------------------------------------- figures
def _bar_png(path):
    img = Image.new("RGB", (300, 190), "white")
    d = ImageDraw.Draw(img)
    d.rectangle([8, 8, 291, 181], outline="black", width=2)
    d.rectangle([50, 110, 110, 175], fill=(60, 110, 200))
    d.rectangle([170, 60, 230, 175], fill=(200, 90, 70))
    img.save(path)


def gen_figures():
    """Page 1: a raster image + caption + an inline cross-reference. Page 2: a vector
    chart (>=6 paths) with axis labels and a 90deg-rotated y-axis title + caption. One
    figure per page so each caption has an unambiguous nearest figure."""
    pdf = os.path.join(OUT, "figures.pdf")
    png = os.path.join(OUT, "_bar.png")
    _bar_png(png)
    c = canvas.Canvas(pdf, pagesize=letter)
    title(c, "Figure Showcase")
    y = PAGE_H - 120
    y = para(c, "This document contains a raster figure and a vector figure. As shown in "
                "Figure 1 the bars differ in height, which the analysis discusses below.", y)
    img_w, img_h = 230, 146
    c.drawImage(png, LM, y - img_h, width=img_w, height=img_h)
    y -= img_h + 14
    c.setFont("Helvetica", 9.5)
    c.drawString(LM, y, "Figure 1: A raster bar chart comparing two measured groups.")
    c.showPage()
    # page 2 — vector figure
    y = PAGE_H - 120
    ox, oy, vw, vh = LM + 50, y - 150, 220, 130
    c.setLineWidth(1)
    c.line(ox, oy, ox + vw, oy)
    c.line(ox, oy, ox, oy + vh)
    for i in range(1, 4):
        gy = oy + vh * i / 4
        c.line(ox, gy, ox + vw, gy)
    c.setFillColorRGB(0.25, 0.45, 0.8)
    for i, bh in enumerate((40, 95, 65, 110)):
        c.rect(ox + 20 + i * 48, oy, 28, bh, fill=1, stroke=1)
    c.setFillColorRGB(0, 0, 0)
    c.setFont("Helvetica", 8)
    for i, lab in enumerate(("Q1", "Q2", "Q3", "Q4")):
        c.drawString(ox + 28 + i * 48, oy - 11, lab)
    c.saveState()
    c.translate(ox - 16, oy + vh / 2 - 20)
    c.rotate(90)
    c.setFont("Helvetica", 8)
    c.drawString(0, 0, "Amplitude")
    c.restoreState()
    yc = oy - 24
    c.setFont("Helvetica", 9.5)
    c.drawString(LM, yc, "Figure 2: A vector line chart with a rotated axis title.")
    c.showPage()
    c.save()
    os.remove(png)
    GT["figures.pdf"] = {
        "fig1_caption": "Figure 1: A raster bar chart comparing two measured groups.",
        "fig2_caption": "Figure 2: A vector line chart with a rotated axis title.",
        "rotated_label": "Amplitude",
        "inline_xref": "As shown in Figure 1 the bars differ",
        "n_figures": 2,
    }


def _vector_chart(c, ox, oy, vw, vh):
    c.setLineWidth(1)
    c.line(ox, oy, ox + vw, oy)
    c.line(ox, oy, ox, oy + vh)
    for i in range(1, 4):
        c.line(ox, oy + vh * i / 4, ox + vw, oy + vh * i / 4)
    c.setFillColorRGB(0.25, 0.45, 0.8)
    for i, bh in enumerate((40, 95, 65, 110)):
        c.rect(ox + 20 + i * 48, oy, 28, min(bh, vh - 4), fill=1, stroke=1)
    c.setFillColorRGB(0, 0, 0)


def gen_figures_onepage():
    """Both figures (raster ABOVE, vector BELOW), each with its own caption directly
    beneath it, on ONE page. Regression guard for caption→figure anchoring: the captions
    must bind to the figure each sits under, not get swapped by a top-edge distance."""
    pdf = os.path.join(OUT, "figures_onepage.pdf")
    png = os.path.join(OUT, "_bar2.png")
    _bar_png(png)
    c = canvas.Canvas(pdf, pagesize=letter)
    title(c, "Two Figures On One Page")
    y = PAGE_H - 120
    img_w, img_h = 220, 140
    c.drawImage(png, LM, y - img_h, width=img_w, height=img_h)
    y -= img_h + 14
    c.setFont("Helvetica", 9.5)
    c.drawString(LM, y, "Figure 1: A raster bar chart comparing two measured groups.")
    y -= 34
    _vector_chart(c, LM + 50, y - 120, 210, 110)
    y -= 120 + 8
    c.setFont("Helvetica", 9.5)
    c.drawString(LM, y, "Figure 2: A vector line chart of the same measurements.")
    c.showPage()
    c.save()
    os.remove(png)
    GT["figures_onepage.pdf"] = {
        "fig1_caption": "Figure 1: A raster bar chart comparing two measured groups.",
        "fig2_caption": "Figure 2: A vector line chart of the same measurements.",
    }


# ------------------------------------------------------------------------------ links
def _assemble_pdf(objs, path):
    """Write a minimal PDF from {objnum: bytes} (numbers contiguous from 1)."""
    body = bytearray(b"%PDF-1.5\n%\xe2\xe3\xcf\xd3\n")
    offsets = {}
    for num in sorted(objs):
        offsets[num] = len(body)
        body += b"%d 0 obj\n" % num + objs[num] + b"\nendobj\n"
    xref_off = len(body)
    n = max(objs) + 1
    body += b"xref\n0 %d\n0000000000 65535 f \n" % n
    for num in range(1, n):
        body += b"%010d 00000 n \n" % offsets[num]
    body += b"trailer\n<< /Size %d /Root 1 0 R >>\nstartxref\n%d\n%%%%EOF\n" % (n, xref_off)
    with open(path, "wb") as f:
        f.write(bytes(body))


def gen_links():
    """Hand-written PDF carrying a real /Names /Dests name tree: an external URI link
    and an internal GoTo to a NAMED destination ("cite.smith2020") on page 2. This is
    the citation-anchor path reportlab can't emit — the internal link must resolve to a
    #slug anchor, never #page-N."""
    pdf = os.path.join(OUT, "links.pdf")
    c1 = (b"BT /F1 12 Tf 72 700 Td (Visit our project homepage for downloads and docs.) Tj "
          b"0 -22 Td (See the Smith 2020 reference and the Methods section below.) Tj ET")
    c2 = (b"BT /F1 14 Tf 72 720 Td (Methods) Tj /F1 12 Tf 72 690 Td "
          b"(This destination section is where the cite anchor resolves, not a page number.) Tj ET")
    objs = {
        1: b"<< /Type /Catalog /Pages 2 0 R /Names << /Dests 8 0 R >> >>",
        2: b"<< /Type /Pages /Kids [3 0 R 5 0 R] /Count 2 >>",
        3: (b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] "
            b"/Resources << /Font << /F1 7 0 R >> >> /Contents 4 0 R /Annots [9 0 R 10 0 R] >>"),
        4: b"<< /Length %d >>\nstream\n%s\nendstream" % (len(c1), c1),
        5: (b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] "
            b"/Resources << /Font << /F1 7 0 R >> >> /Contents 6 0 R >>"),
        6: b"<< /Length %d >>\nstream\n%s\nendstream" % (len(c2), c2),
        7: b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
        8: b"<< /Names [ (cite.smith2020) [5 0 R /XYZ 72 730 0] ] >>",
        9: (b"<< /Type /Annot /Subtype /Link /Rect [72 696 420 714] /Border [0 0 0] "
            b"/A << /S /URI /URI (https://example.com/distillpdf) >> >>"),
        10: (b"<< /Type /Annot /Subtype /Link /Rect [72 674 420 692] /Border [0 0 0] "
             b"/A << /S /GoTo /D (cite.smith2020) >> >>"),
    }
    _assemble_pdf(objs, pdf)
    GT["links.pdf"] = {
        "uri": "https://example.com/distillpdf",
        "dest_name": "cite.smith2020",
        "dest_page": 2,
        "uri_text": "Visit our project homepage",
        "internal_text": "Methods section",
    }


# -------------------------------------------------------------------------- typography
def gen_typography():
    """Superscript / subscript (via text rise so they stay on one line), accented Latin
    characters, and de-hyphenation across a line break."""
    pdf = os.path.join(OUT, "typography.pdf")
    c = canvas.Canvas(pdf, pagesize=letter)
    title(c, "Typography Showcase")
    y = PAGE_H - 120
    y = para(c, "This fixture exercises scripts, accented characters and de-hyphenation.", y)
    # superscript on one line via setRise
    t = c.beginText(LM, y)
    t.setFont(BODY_F, 12); t.textOut("The relation E = mc")
    t.setRise(4); t.setFont(BODY_F, 7); t.textOut("2")
    t.setRise(0); t.setFont(BODY_F, 12); t.textOut(" links energy and mass.")
    c.drawText(t)
    y -= LEAD + 6
    # subscript on one line via setRise
    t = c.beginText(LM, y)
    t.setFont(BODY_F, 12); t.textOut("The molecule H")
    t.setRise(-3); t.setFont(BODY_F, 7); t.textOut("2")
    t.setRise(0); t.setFont(BODY_F, 12); t.textOut("O is common.")
    c.drawText(t)
    y -= LEAD + 6
    y = para(c, "Accented words: café, résumé, naïve, Pérez, fjord — all intact.",
             y, size=12)
    # de-hyphenation: hyphen at line end, continuation on the next line of one paragraph
    c.setFont(BODY_F, 12)
    c.drawString(LM, y, "The pipeline performs auto-")
    y -= LEAD
    c.drawString(LM, y, "matic reconstruction of words that hyphenation split across lines.")
    c.showPage()
    c.save()
    GT["typography.pdf"] = {
        "accents": ["café", "résumé", "naïve", "Pérez", "fjord"],
        "dehyphenated": "automatic",
        "not_present": "auto- matic",
        "superscript_base": "mc",
        "subscript_base": "H",
    }


# ------------------------------------------------------------------------- two columns
def gen_twocol():
    """Two-column body prose via platypus frames (each flowable cm-positioned). The
    whole left column must be read before the right column, and the page must NOT be
    mistaken for a table."""
    pdf = os.path.join(OUT, "twocol.pdf")
    styles = getSampleStyleSheet()
    body = styles["BodyText"]
    left = ["LEFTONE Reading order in a two-column layout must follow each column from "
            "top to bottom before crossing to the next column, which this fixture checks.",
            "LEFTTWO The second left-column paragraph continues with ordinary body prose "
            "so the left column has a clear and substantial vertical extent on the page.",
            "LEFTTHREE The third left-column paragraph closes this side of the page before "
            "the reader crosses the central gutter into the right-hand column of text."]
    right = ["RIGHTONE The right column is read only after the entire left column has been "
             "consumed, the precise reading-order property that this fixture is verifying.",
             "RIGHTTWO The second right-column paragraph adds more flowing body prose to "
             "keep the two columns close in height and the central gutter clearly empty.",
             "RIGHTTHREE The final right-column paragraph ends the page with further plain "
             "sentences so neither column is unusually short relative to the other one."]
    story = [Paragraph(p, body) for p in left + right]
    doc = BaseDocTemplate(pdf, pagesize=letter, topMargin=110, bottomMargin=72)
    fw = (COL_W - 36) / 2
    fh = PAGE_H - 110 - 72
    doc.addPageTemplates(PageTemplate(frames=[
        Frame(LM, 72, fw, fh, id="L"),
        Frame(LM + fw + 36, 72, fw, fh, id="R"),
    ]))
    doc.build(story)
    GT["twocol.pdf"] = {
        "order": ["LEFTONE", "LEFTTWO", "LEFTTHREE", "RIGHTONE", "RIGHTTWO", "RIGHTTHREE"],
    }


# ------------------------------------------------------------------------------- math
def gen_math():
    """An ASCII display equation (relational '=', an equation number) that must NOT
    become a table or a heading, and a 'Theorem 1.' lead that must NOT be a standalone
    heading. Symbols are ASCII so built-in Helvetica renders them faithfully."""
    pdf = os.path.join(OUT, "math.pdf")
    c = canvas.Canvas(pdf, pagesize=letter)
    title(c, "Convergence Analysis")
    y = PAGE_H - 120
    y = heading(c, "1 Analysis", y)
    y = para(c, "We bound the loss with the following inequality, derived in the appendix.", y)
    # equation with a real subscript (text rise) so this math doc keeps its notation
    t = c.beginText(LM + 40, y)
    t.setFont(BODY_F, 12); t.textOut("L(w) = S(w) + a * R(x")
    t.setFont(BODY_F, 8); t.setRise(-3); t.textOut("i")
    t.setRise(0); t.setFont(BODY_F, 12); t.textOut(") + b      (1)")
    c.drawText(t)
    y -= LEAD + 8
    y = para(c, "Theorem 1. The estimator is consistent under the stated assumptions and "
                "converges to the true parameter as the sample size grows without bound.", y)
    y = para(c, "The remaining discussion is ordinary body prose following the theorem "
                "statement and should be extracted as a paragraph in reading order.", y)
    c.showPage()
    c.save()
    GT["math.pdf"] = {
        "title": "Convergence Analysis",
        "section": "1 Analysis",
        "equation_fragment": "S(w)",
        "theorem_text": "The estimator is consistent under the stated assumptions",
    }


# ---------------------------------------------------------------------------- numeric
def gen_numeric():
    """A borderless numeric table for word-span granularity (no span may pack >1 numeric
    token) and decimal integrity (a decimal must never render as ' : ')."""
    pdf = os.path.join(OUT, "numeric.pdf")
    c = canvas.Canvas(pdf, pagesize=letter)
    title(c, "Numeric Results")
    y = PAGE_H - 130
    headers = ["System", "Acc", "F1", "Loss"]
    rows = [["BaseNet", "84.6", "83.4", "0.21"],
            ["WideNet", "88.2", "87.9", "0.18"],
            ["DeepNet", "91.5", "90.7", "0.15"],
            ["MegaNet", "92.3", "91.8", "0.12"]]
    col_x = [LM, LM + 150, LM + 220, LM + 290]
    c.setFont("Helvetica-Bold", 10)
    for cx, h in zip(col_x, headers):
        c.drawString(cx, y, h)
    y -= LEAD
    c.setFont("Helvetica", 10)
    for row in rows:
        for cx, cell in zip(col_x, row):
            c.drawString(cx, y, cell)
        y -= LEAD
    c.showPage()
    c.save()
    GT["numeric.pdf"] = {
        "header": headers, "rows": rows,
        "decimals": ["84.6", "0.21", "92.3", "0.12"],
    }


def main():
    gen_headings()
    gen_lists()
    gen_twolists()
    gen_figures()
    gen_figures_onepage()
    gen_links()
    gen_typography()
    gen_twocol()
    gen_math()
    gen_numeric()
    with open(os.path.join(OUT, "groundtruth.json"), "w") as f:
        json.dump(GT, f, indent=2)
    print(f"generated {len(GT)} fixture PDFs + groundtruth.json -> {OUT}")


if __name__ == "__main__":
    main()
