#!/usr/bin/env bash
# Dev loop: build distillpdf into the local venv, then run the owned test suite (pytest).
#
# tests/ is fully self-contained — every fixture is generated by us and committed (see
# gen_demo.py / gen_tables.py / gen_fixtures.py), so this is exactly what CI runs. The
# deeper corpus gates and competitor benchmarks are local-only under the gitignored
# ../benchmarking/ (run benchmarking/corpus_tests/run.sh for those). --no-build skips the
# rebuild.
set -e
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
VENV="$ROOT/.venv"
PY="$VENV/bin/python"

[ -d "$VENV" ] || python3 -m venv "$VENV"

if [ "${1:-}" != "--no-build" ]; then
  # Build a wheel and force-reinstall it (NOT `maturin develop`: its editable layout can
  # leave a stale .so loaded so source edits silently don't take effect). Wheel path is
  # reproducible via the latest-mtime glob.
  "$VENV/bin/pip" -q install maturin pytest >/dev/null 2>&1 || true
  ( cd "$ROOT" \
    && VIRTUAL_ENV="$VENV" "$VENV/bin/maturin" build --release 2>&1 | grep -iE "error|Built wheel" )
  WHEEL="$(ls -t "$ROOT/target/wheels/"*.whl | head -1)"
  "$VENV/bin/pip" install -q --force-reinstall --no-deps "$WHEEL" >/dev/null
  "$PY" -c "import distillpdf" || { echo "distillpdf import failed after build"; exit 1; }
fi

exec "$PY" -m pytest "$ROOT/tests" -q
